#!/bin/bash

### repurpose arguments to variables 
X=$1

### redirect standard output to a file to print then later remove
c=`cat /root/1`
r=`rm -fr /root/1`

##
### main controller create function which creates a vm with `--hostgroup-id=2` (foreman) using compute resource `--compute-resource-id=1` (oVirt) 

__controller() {
for x in "$X"; do $r; hammer host create --hostgroup-id=2 --name="$x" --compute-resource-id=1 --compute-attributes="start=1" --interface="name=eth0,network=provisioning" >1 >/root/1 ; done &
PID=$!
i=1
sp="/-\|"
echo -n ' '
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
}

##
### controller label function

__controller_label () {
datestart=`date +%H:%M:%S`
echo -e "STAGE 1 [build] ****************************************************************"
echo -e "PROVISIONING NODE [\033[01m$X\033[0m] ******************************************"
echo -e "STARTED [$datestart] ***********************************************************"
}

##
### foreman finished creating host label function

__finished_label() {
echo -e "BUILDING NODE [$c \033[01;32m$X\033[0m] ****************************************"
}

###
### add an entry to ansible host file for handoff[1]

__host() {
echo $X.irondung.net >> /etc/ansible/hosts
}

##
### ansible-playbook function

__playbook_create() {
cat >/etc/ansible/$X-packstack.yml<< EOF
---

- hosts: $X.irondung.net
  remote_user: root
  connection: local
  tasks:
   - name: STAGE 1 Ansible is polling for build completion
     local_action: wait_for path=/var/log/foreman/production.log search_regex="$X.irondung.net is Built" delay=5 timeout=900
     become: sudo

   - name: STAGE 1 COMPLETE Ansible is waiting for the host to reboot
     local_action: wait_for port=22 host="$X.irondung.net" state=started search_regex=OpenSSH delay=35 timeout=60
     become: sudo

   - name: STAGE 2 Configuration Ansible is installing Red Hat OpenStack (Liberty) in a non-ha single node configuration
     shell: " rm -fr /root/.ssh/known_hosts ; sshpass -pNSAbegone3# ssh-copy-id  -o StrictHostKeyChecking=no root$X.irondung.net ; ssh -o StrictHostKeyChecking=no root@$X.irondung.net 'sh /root/ansible.sh' 2>/dev/null "
     args:
       creates: /etc/ansible/.packstack-2-$X
EOF
}

##
### start ansible function

__ansible_start() {
ansible-playbook -s /etc/ansible/$X-packstack.yml &
PID=$!
i=1
sp="/-\|"
echo -n ' '
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
}

##
### sleep 10 function 

__sleep_10() {
sleep 10 &
PID=$!
i=1
sp="/-\|"
echo -n ' '
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
}

##
### Finalize build and exit

__exit_0() {
sleep 10 &
PID=$!
i=1
sp="/-\|"
echo -n ' '
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
exit $?
}

echo -e "STAGE 2 COMPLETE **********************************************************"
echo -e "[\033[01m$X\033[0m] is now fully deployed"
echo -e "TAKE ACTION: **************************************************************"
echo -e "[\033[01m`sshpass $SSHPASS root@$X.irondung.net`\033[0m]"

##
### main

__controller_label
__controller
__sleep_10
__finished_label
__host
__playbook_create
__ansible_start
__exit_0
